#!/usr/bin/env bash

read -p "Start all workers now? [y/N] " -r start
if [[ "${start,,}" == "y" ]] ; then
    for wrepopath in ~/.lotusworkers/*; do

        wreponame=$(basename $wrepopath)
        if [ ! -f "$wrepopath/$wreponame.env" ]; then
            echo "Skipping $wreponame..."
            continue
        fi

        source $wrepopath/$wreponame.env
        if [ -z "$LOTUS_CUSTOM_CPUGROUP" ]; then
            nohup lotus-worker run \
                --listen=${LOTUS_CUSTOM_IP:=0.0.0.0}:${LOTUS_CUSTOM_PORT:=3400} \
                --addpiece=${LOTUS_CUSTOM_ADDPIECE:=false} \
                --precommit1=${LOTUS_CUSTOM_PRECOMMIT1:=false} \
                --precommit2=${LOTUS_CUSTOM_PRECOMMIT2:=false} \
                --commit=${LOTUS_CUSTOM_COMMIT:=false} \
                --unseal=${LOTUS_CUSTOM_UNSEAL:=false} \
                --replica-update=${LOTUS_CUSTOM_REPLICA_UPDATE:=false} \
                --prove-replica-update2=${LOTUS_CUSTOM_PROVE_REPLICA_UPDATE2:=false} \
                --regen-sector-key=${LOTUS_CUSTOM_REGEN_SECTOR_KEY:=false} \
                --winningpost=${LOTUS_CUSTOM_WINNINGPOST:=false} \
                --windowpost=${LOTUS_CUSTOM_WINDOWPOST:=false} > $wrepopath/$wreponame.log 2>&1 &
        else
            nohup cgexec -g cpuset:${LOTUS_CUSTOM_CPUGROUP:=all} --sticky lotus-worker run \
                --listen=${LOTUS_CUSTOM_IP:=0.0.0.0}:${LOTUS_CUSTOM_PORT:=3400} \
                --addpiece=${LOTUS_CUSTOM_ADDPIECE:=false} \
                --precommit1=${LOTUS_CUSTOM_PRECOMMIT1:=false} \
                --precommit2=${LOTUS_CUSTOM_PRECOMMIT2:=false} \
                --commit=${LOTUS_CUSTOM_COMMIT:=false} \
                --unseal=${LOTUS_CUSTOM_UNSEAL:=false} \
                --replica-update=${LOTUS_CUSTOM_REPLICA_UPDATE:=false} \
                --prove-replica-update2=${LOTUS_CUSTOM_PROVE_REPLICA_UPDATE2:=false} \
                --regen-sector-key=${LOTUS_CUSTOM_REGEN_SECTOR_KEY:=false} \
                --winningpost=${LOTUS_CUSTOM_WINNINGPOST:=false} \
                --windowpost=${LOTUS_CUSTOM_WINDOWPOST:=false} > $wrepopath/$wreponame.log 2>&1 &
        fi
    done
fi