export FIL_PROOFS_MULTICORE_SDR_PRODUCERS=2
export FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1
export FIL_PROOFS_USE_GPU_TREE_BUILDER=1
export FIL_PROOFS_MAXIMIZE_CACHING=1
export LOTUS_CUSTOM_IP=10.10.0.81
#export LD_LIBRARY_PATH=/usr/local/cuda-11.2/lib64
#export CUDA_HOME=/usr/local/cuda
